/*
Copyright (c) 2011 Cimaron Shanahan

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

var compiler = (function() {
	
	var preprocessor;
	var lexer;
	var parser;

	var yyextra = {
		scanner : null,
		translation_unit : [],
		symbols : {
			variables : {},
			functions : {},
			types : {}
		},
		
		es_shader : true,		
		language_version : 110,
		version_string : '',
		
	};
	var ES = yyextra.es_shader;

	var yylval = {};
	var token;

	var copy = function(target, source) {
		for (var i in source) {
			target[i] = source[i];	
		}
		return target;
	};
	
	var yylex = function(_yylval, yylloc, scanner) {
		parser.yylval = copy(yylval, _yylval);
		var result = lexer.lex();
		copy(yylloc, lexer.yylloc);
		return result;
	};

	var yyerror = function(yylloc, state, error) {
		compiler.errors.push(error + " at line " + yylloc.first_line + " column " + yylloc.first_column);
	};

	var YYPRINT = function(yyoutput, yytoknum, yyvaluep) {
		if (yyvaluep.print) {
			yyvaluep.print();
		} else if (JSON.stringify) {
			fprintf(stdout, JSON.stringify(yyvaluep));
		} else {
			fprintf(stdout, yyvaluep + "");
		}
	}

	//These are used in the lexer, but since the lexer is autogenerated, and doesn't allow
	//additional custom code, we need to provide them here
	var KEYWORD = function(reserved_version, allowed_version, token) {
		if (typeof allowed_version != 'number') {
			var aES = allowed_version[1]; allowed_version = allowed_version[0]
		}
		if (typeof reserved_version != 'number') {
			var rES = reserved_version[1]; reserved_version = reserved_version[0]
		}

		if (yyextra.language_version >= allowed_version || (aES && ES)) {
			return token;
		} else if (yyextra.language_version >= reserved_version || (rES && ES)) {
			this.error(yylloc, yyextra, "Illegal use of reserved word '%s'", yytext);
			return ERROR_TOK;
		} else {
			yylval.identifier = this.lexer.yytext;
			return this.classify_identifier(this.yyextra, this.lexer.yytext);
		}
	};

	var classify_identifier = function(state, name) {
		if (state.symbols.variables[name] || state.symbols.functions[name]) {
			return parser.yytokentype.IDENTIFIER;
		} else if (state.symbols.types[name]) {
			return parser.yytokentype.TYPE_IDENTIFIER;
		} else {
			return parser.yytokentype.NEW_IDENTIFIER;
		}
	};




	var compiler = {

		errors : [],

		//expose to lexer/parser
		yyextra : yyextra,		
		yylval : yylval,		
		token : token,
		KEYWORD : KEYWORD,		
		classify_identifier : classify_identifier,
		parseError : function(str, hash) {
			yyerror(lexer.yylloc, yyextra, str);
		},

		setPreprocessor : function(p) {
			this.preprocessor = preprocessor = p;
		},

		setLexer : function(l) {
			this.lexer = lexer = l;
			l.yy = this;
		},

		setParser : function(p) {
			this.parser = parser = p;
			this.parser.extern('yylex', yylex);
			this.parser.extern('yyerror', yyerror);
			this.parser.extern('YYPRINT', YYPRINT);
			this.token = p.yytokentype;
		},
 
		compile : function(src) {
			src = preprocessor.process(src);
			lexer.setInput(src);
			var result = parser.yyparse(yyextra);
			return result;
		}
		
	}
	
	return compiler;
})();




